layout_spectrum: 1
color:
  saturation: 0.1575027
  brandStrength: 0.1305888
  lightness: 0.2007169
  rhythmicContrast: 0.8369176
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 0.6756272
name: Lyra
