name: Lyra
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6756272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231d53'
    - '#918ea9'
    - '#c8c7d4'
    - '#54b847'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
